#!/bin/bash

is_sourced() {
  [[ "${BASH_SOURCE[0]}" != "${0}" ]]
}

if ! is_sourced; then
    echo "Please run this script as source ./scripts/bootstrap"
    exit 1
fi

git submodule update --recursive --init
git config core.hooksPath .githooks

python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt

sudo apt install cmake